IspcaIKEA/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from two_factor.urls import urlpatterns as tf_urls



urlpatterns = [
    path('', include(tf_urls)),
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    
]

urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT) 

core/urls.py
from django.urls import path
from core.views import about_us_view, place_order, checkout_view, update_cart, delete_item_from_cart, cart_view, add_to_cart, add_review, index, product_list_view, product_detail_view, category_list_view,category_product_list_view

app_name = "core"

urlpatterns = [

    # Homepage
    path("", index, name="index"),
    path("products/", product_list_view, name="product_list"),
    path("products/<pid>/", product_detail_view, name="product_detail"),
    path("about-us/", about_us_view, name="about_us"),

    # Category
    path("category/", category_list_view, name="category_list"),
    path("category/<cid>/", category_product_list_view, name="category_product_list"),

    #add review
    path("add-review/<pid>", add_review, name="add-review"),
    #add to cart
    path("add-to-cart", add_to_cart, name="add-to-cart"),
    
    #cartview
    path("cart/", cart_view, name="cart"),

    #detele item from cart
    path("delete-from-cart", delete_item_from_cart, name="delete-from-cart"),

    #update cart
    path("update-cart", update_cart, name="update-cart"),

    #checkout cart
    path("checkout/", checkout_view, name="checkout"),

    #place order
    path("place-order", place_order, name="place_order"),
]

core/models.py

from django.db import models
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from userauths.models import User

# Create your models here.


RATING= (
    (20, "★☆☆☆☆"),
    (40, "★★☆☆☆"),
    (60, "★★★☆☆"),
    (80, "★★★★☆"),
    (100, "★★★★★"),
)

class Category(models.Model):
    cid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="cat", alphabet="abcdefgh12345") #cid = category id
    title = models.CharField(max_length=100, default="Moveis") #titulo 
    image = models.ImageField(upload_to="category",default="category.jpg")

    class Meta:
        verbose_name_plural = "Categories"
    
    def category_image(self):
        return mark_safe('<img src="%s" width="50" height="60" >' % (self.image.url) )
    
    def __str__(self):
        return self.title
    
    
class Product(models.Model):
     pid = ShortUUIDField(unique=True, length=10, max_length=20, prefix="prd", alphabet="abcdefgh12345") #pid = product id
     
     category= models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="category")
     
     title = models.CharField(max_length=100, default="Cama") #titulo 
     image = models.ImageField(upload_to="product", default="product.jpg")
     description = models.TextField(null=True, blank=True, default="Produto")

     price = models.DecimalField(max_digits=999999, decimal_places=2,default="1.99")
     old_price = models.DecimalField(max_digits=999999, decimal_places=2,default="2.99")
     
     specifications = models.TextField(null=True, blank=True)
     stock_count = models.CharField(max_length=100, default="10", null=True, blank=True)
     

     status = models.BooleanField(default=True)
     in_stock = models.BooleanField(default=True)
     featured = models.BooleanField(default=False)

     sku = ShortUUIDField(unique=True, length=4, max_length=10, prefix="sku", alphabet="1234567890")
     
     class Meta:
        verbose_name_plural = "Products"
    
     def product_image(self):
            return mark_safe('<img src="%s" width="50" height="60" >' % (self.image.url) )
    
     def __str__(self):
        return self.title
     
     def get_percentage(self):
         new_price = 100 - (( self.price / self.old_price) * 100)
         return new_price
     
class ProductImages(models.Model):
    images = models.ImageField(upload_to="product_images",default="product.jpg")
    product = models.ForeignKey(Product, related_name="p_images", on_delete= models.SET_NULL, null=True)
    
    class Meta:
        verbose_name_plural = "Product Images"

    
####################################### Cart order ########################################
####################################### Cart order ########################################
####################################### Cart order ########################################


class CartOrder(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)   
    price = models.DecimalField(max_digits=999999, decimal_places=2,default="1.99")
    paid_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Cart Order"

class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrder, on_delete=models.CASCADE)
    invoice_no = models.CharField(max_length=200)
    product_status = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=999999, decimal_places=2,default="1.99")
    total = models.DecimalField(max_digits=999999, decimal_places=2,default="1.99")
    
    class Meta:
        verbose_name_plural = "Cart Order Items" 

    def oder_img(self):
        return mark_safe('<img src="/media/%s" width="50" height="60" >' % (self.image) ) 
    
####################################### Wishlist & Reviews ########################################
####################################### Wishlist & Reviews ########################################
####################################### Wishlist & Reviews ########################################

    
class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null = True, related_name="reviews")
    review = models.TextField()
    rating = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Product Reviews"
    def __str__(self):
        return self.product.title
    def get_rating(self):
        return self.rating
    

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null = True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Wishlists"
    def __str__(self):
        return self.product.title


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
    address = models.CharField(max_length=100, null= True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Address"    


core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Escreva um comentario"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from core.models import Product, Category, CartOrderItems, CartOrder, Wishlist,ProductImages, Address, ProductReview
from django.db.models import Count, Avg
from core.forms import ProductReviewForm
from django.contrib import messages
from django.template.loader import render_to_string

# Create your views here.

def index(request):
    products = Product.objects.filter(featured = True).order_by("-id")

    context = {
        "products": products #key : object
    }
    return render(request, 'core/index.html', context)


def product_list_view(request):
     products = Product.objects.filter().order_by("-id")

     context = {
        "products": products #key : object
    }
     
     return render(request, 'core/product-list.html', context)
    
def category_list_view(request):
     categories = Category.objects.all()

     context = {
        "categories": categories  #key : object
    }
     
     return render(request, 'core/category-list.html', context)
    
def category_product_list_view(request, cid):
     category = Category.objects.get(cid=cid)
     products = Product.objects.filter(category=category)

     context = {
          "category":category,
          "products":products
     }

     return render(request, "core/category-product-list.html", context)

def product_detail_view(request, pid):
     
     product = Product.objects.get(pid=pid)
     p_images = product.p_images.all()

     #Getting all reviews
     reviews = ProductReview.objects.filter(product=product)

     #Getting average reviews
     average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

     #product revire form
     review_form = ProductReviewForm()

     context = {
          "product":product,
          "p_images":p_images,
          "reviews":reviews,
          "review_form":review_form,
          "average_rating": average_rating
     }

     return render(request, "core/product-detail.html", context)

def add_review(request, pid):
     product = Product.objects.get(pid=pid)
     user = request.user

     review = ProductReview.objects.create(
          user= user,
          product= product,
          review = request.POST['review'],
          rating = request.POST['rating'],
     )

     context = {
          'user': user.username,
          'review': request.POST['review'],
          'rating': request.POST['rating'],
     }

     average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

     return JsonResponse(
          {
          'bool': True,
          'context': context,
          'avg_reviews': average_reviews
          }
     )


def add_to_cart(request):
     cart_product = {}

     cart_product[str(request.GET['id'])] ={
          'title':request.GET['title'],
          'qty':request.GET['qty'],
          'price':request.GET['price'],
          'image':request.GET['image'],
          'pid':request.GET['pid'],
     }

     if 'cart_data_obj' in request.session:
          if str(request.GET['id']) in request.session['cart_data_obj']:
               cart_data = request.session['cart_data_obj']
               cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
               cart_data.update(cart_data)
               request.session['cart_data_obj'] = cart_data
          else:
               cart_data = request.session['cart_data_obj']
               cart_data.update(cart_product)
               request.session['cart_data_obj'] = cart_data
     
     else:
          request.session['cart_data_obj'] = cart_product
     return JsonResponse({"data":request.session['cart_data_obj'],'totalcartItems':len(request.session['cart_data_obj'])})


def cart_view(request):
     cart_total_amount = 0
     if 'cart_data_obj' in request.session:

          for product_id, item in request.session['cart_data_obj'].items():
               cart_total_amount += int(item['qty']) * float(item['price'])
          return render(request,"core/cart.html", {"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
     else:
          messages.warning(request, "Não tem nada no carrinho")
          return redirect("core:index")
     

def delete_item_from_cart(request):
     product_id = str(request.GET['id'])
     if 'cart_data_obj' in request.session:
          if product_id in request.session['cart_data_obj']:
               cart_data = request.session['cart_data_obj']
               del request.session['cart_data_obj'][product_id]
               request.session['cart_data_obj'] = cart_data
    
     cart_total_amount = 0
     if 'cart_data_obj' in request.session:

          for product_id, item in request.session['cart_data_obj'].items():
               cart_total_amount += int(item['qty']) * float(item['price'])

     context = render_to_string("core/async/cart-list.html",{"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount} )

     return JsonResponse({"data": context, 'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})  


def update_cart(request):
     product_id = str(request.GET['id'])
     product_qty = request.GET['qty']

     if 'cart_data_obj' in request.session:
          if product_id in request.session['cart_data_obj']:
               cart_data = request.session['cart_data_obj']
               cart_data[str(request.GET['id'])]['qty'] = product_qty
               request.session['cart_data_obj'] = cart_data
    
     cart_total_amount = 0
     if 'cart_data_obj' in request.session:

          for product_id, item in request.session['cart_data_obj'].items():
               cart_total_amount += int(item['qty']) * float(item['price'])

     context = render_to_string("core/async/cart-list.html",{"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount} )

     return JsonResponse({"data": context, 'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})



def checkout_view(request):
         
     cart_total_amount = 0
     if 'cart_data_obj' in request.session:

          for product_id, item in request.session['cart_data_obj'].items():
               cart_total_amount += int(item['qty']) * float(item['price'])

          return render(request,"core/checkout.html", {"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})


def place_order(request):
         
     cart_total_amount = 0
     total_amount = 0
     if 'cart_data_obj' in request.session:
          
          order = CartOrder.objects.create(
               user = request.user,
               price=total_amount
          )

          for product_id, item in request.session['cart_data_obj'].items():
               cart_total_amount += int(item['qty']) * float(item['price'])

               items=CartOrderItems.objects.create(
                    order=order,
                    item=item['title'],
                    image=item['image'],
                    qty=item['qty'],
                    price=item['price'],
                    total=float(item['qty']) * float(item['price'])
               )

          JsonResponse({"cart_data":request.session['cart_data_obj'],'totalcartitems':len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
          return redirect("core:index") 
     

def about_us_view(request):
     
     return render(request, 'core/about-us.html')

templates/core/about-us.html
<h1>É po 20 , obrigado</h1>

templates/core/cart.html
{%extends 'partials/base.html' %} {% load static %} {% block content %}

    <main class="main" id="cart_list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="{% url 'core:index' %}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Produtos
                    <span></span> Carrinho
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Carrinho</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">Existem <span class="text-brand">{{totalcartitems}}</span> produtos no seu carrinho</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Produto</th>
                                    <th scope="col">Preço </th>
                                    <th scope="col"class="text-center">Quantidade</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col">Refresh</th>
                                    <th scope="col" class="end">Remover</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id,item in cart_data.items %}
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product_detail' item.pid %}">{{ item.title }}</a></h6>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">{{item.price}}€</h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="mr-15">
                                             <input type="number" class="w-25 product-qty-{{product_id}}" value="{{item.qty}}" id="product-quantity">
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand">{% widthratio item.price 1 item.qty %}€</h4>
                                    </td>
                                    <td class="action text-center" data-title="Update"><button style="border: none; background: none;" class="text-body update-product" data-product="{{product_id}}"><i class="fi-rs-refresh"></i></button></td>
                                    <td class="action text-center" data-title="Remove"><button style="border: none; background: none;" class="text-body delete-product" data-product="{{product_id}}"><i class="fi-rs-trash"></i></button></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <div class="cart-action d-flex justify-content-between">
                        <a class="btn " href="{% url 'core:product_list' %}"><i class="fi-rs-arrow-left mr-10"></i>Continuar a comprar</a>
                        <h6 class="text-body"><a href="{% url 'core:cart' %}" class="text-muted"><i class="fi-rs-refresh mr-5"></i>Refresh</a></h6>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">{{cart_total_amount|floatformat:2}}€</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Gratis</h4</td> </tr> <tr>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">{{cart_total_amount|floatformat:2}}€</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {% if totalcartitems %}
                        <a href="{% url 'core:checkout' %}" class="btn mb-20 w-100">Ir para o CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                        {% endif %}
                </div>
            </div>
        </div>
    </main>
  {% endblock content %}

templates/core/category-product-list.html
{%extends 'partials/base.html' %} {% load static %} {% block content %}

<main class="main">
  <div class="page-header mt-30 mb-50">
    <div class="container">
      <div class="archive-header">
        <div class="row align-items-center">
          <div class="col-xl-3">
            <h1 class="mb-15">{{ category.title }}</h1>
            <div class="breadcrumb">
              <a href="{% url 'core:index' %}" rel="nofollow"
                ><i class="fi-rs-home mr-5"></i>Home</a
              >
              <span></span> Categorias <span></span> {{ category.title }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container mb-30">
    <div class="row">
      <div class="col-12">
        <div class="shop-product-fillter">
          <div class="totall-product">
            <p>
              Encontramos
              <strong class="text-brand">{{ products.count }}</strong> produtos
              para si!
            </p>
          </div>
          <div class="sort-by-product-area">
            <div class="sort-by-cover mr-10">
              <div class="sort-by-product-wrap">
                <div class="sort-by">
                  <span><i class="fi-rs-apps"></i>Show:</span>
                </div>
                <div class="sort-by-dropdown-wrap">
                  <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                </div>
              </div>
              <div class="sort-by-dropdown">
                <ul>
                  <li><a class="active" href="#">50</a></li>
                  <li><a href="#">100</a></li>
                  <li><a href="#">150</a></li>
                  <li><a href="#">200</a></li>
                  <li><a href="#">All</a></li>
                </ul>
              </div>
            </div>
            <div class="sort-by-cover">
              <div class="sort-by-product-wrap">
                <div class="sort-by">
                  <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                </div>
                <div class="sort-by-dropdown-wrap">
                  <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                </div>
              </div>
              <div class="sort-by-dropdown">
                <ul>
                  <li><a class="active" href="#">Featured</a></li>
                  <li><a href="#">Price: Low to High</a></li>
                  <li><a href="#">Price: High to Low</a></li>
                  <li><a href="#">Release Date</a></li>
                  <li><a href="#">Avg. Rating</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="row product-grid">
          {% for p in products %}
          <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
            <div class="product-cart-wrap mb-30">
              <div class="product-img-action-wrap">
                <div class="product-img product-img-zoom">
                  <a href="{% url 'core:product_detail' p.pid %}">
                    <img class="default-img" src="{{ p.image.url }}" alt="" />
                    <img class="hover-img" src="{{ p.image.url }}" alt="" />
                  </a>
                </div>
                <div
                  class="product-badges product-badges-position product-badges-mrg"
                >
                  <span class="hot">-{{p.get_percentage| floatformat:0}}%</span>
                </div>
              </div>
              <div class="product-content-wrap">
                <div class="product-category">
                  <a href="{% url 'core:category_product_list' category.cid %}"
                    >{{p.category}}</a
                  >
                </div>
                <h2>
                  <a href="{% url 'core:product_detail' p.pid %}"
                    >{{p.title}}</a
                  >
                </h2>
                <div class="product-rate-cover">
                  <div class="product-rate d-inline-block">
                    <div class="product-rating" style="width: 90%"></div>
                  </div>
                  <span class="font-small ml-5 text-muted"> (4.0)</span>
                </div>
                <div class="product-card-bottom">
                  <div class="product-price">
                    <span class="current-product-price-{{ p.id }}"
                      >{{p.price}}</span
                    ><span>€</span>
                    <span class="old-price">{{p.old_price}}</span>
                  </div>
                  <div class="add-cart">
                    <input
                      type="hidden"
                      value="1"
                      class="w-25 mb-20
                    product-quantity-{{p.id}}"
                    />
                    <input
                      type="hidden"
                      class="product-pid-{{p.id}}"
                      value="{{p.pid}}"
                    />
                    <input
                      type="hidden"
                      class="product-image-{{p.id}}"
                      value="{{p.image.url}}"
                    />
                    <input
                      type="hidden"
                      class="product-id-{{p.id}}"
                      value="{{ p.id }}"
                    />
                    <input
                      type="hidden"
                      class="product-title-{{p.id}}"
                      value="{{ p.title }}"
                    />
                    <button
                      class="button add-to-cart-btn add-cart"
                      data-index="{{ p.id }}"
                    >
                      <i class="fi-rs-shopping-cart mr-5"></i>Add
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <!--end product card-->
        </div>
        <!--product grid-->
      </div>
    </div>
  </div>
</main>
{% endblock content %}